import type { Metadata } from "next";
import { Lora } from 'next/font/google'
import "./globals.css";

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
})


export const metadata: Metadata = {
  title: "Edu Smart",
  description: "Generated by Edu Smart",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={lora.className}
      >
        {children}
      </body>
    </html>
  );
}
